### ISSUE TITLE
Consider upgrading CI to NodeJS 14

### ISSUE THREAD

**Issue by bershanskiy** [Maps4HTML/mapml-extension#29]
Currently CI uses NodeJS 12:
https://github.com/Maps4HTML/mapml-extension/blob/219628c532ae9c2766d68678e07ccb9806679b3b/.github/workflows/ci-testing.yml#L15
NodeJS 12 reached ["end of life in April"](https://nodejs.org/es/blog/release/v12.13.0/). Should NodeJS be bumped to 14? NodeJS 14 is the current "Maintenance LTS" and will be supported until April 2023.

**Comment by prushforth** [comment]
Definitely!
