### ISSUE TITLE
Clearing storage leads to a different internal state than after first install

### ISSUE THREAD

**Issue by bershanskiy** [Maps4HTML/mapml-extension#34]
There is a slight discrepancy between extension `options` right after first install and after storage reset. Specifically:

On first install (inside of `chrome.runtime.onInstalled` listener) extension sets `options` to `{renderMap: true}`:
https://github.com/Maps4HTML/mapml-extension/blob/badce0964af89dd9cbb62b86fbeb11751e5c867f/src/background.js#L46
But the popup/settings UI just clears the storage entirely in `resetStorage()`:
https://github.com/Maps4HTML/mapml-extension/blob/badce0964af89dd9cbb62b86fbeb11751e5c867f/src/popup.js#L51

This means that the following scenario is possible once extension is released on some extension store:
1. User installs extension for the first time and has `renderMap` option enabled
2. User clears storage (removing `options`) and gets `renderMap` option disabled and uses extension for a while
3. Extension gets updated, `chrome.runtime.onInstalled` listener is called, sees that `options` are not there, populates them with default enabling `renderMap`.

This leads to change in settings upon update (which is invisible to user), which can be considered a bug.

**Comment by bershanskiy** [comment]
This is trivial to fix, if you consider this a bug I can prepare a PR.

**Comment by prushforth** [comment]
I  am actually wondering why we have a clear storage button in the first place.  It doesn't seem like we have a lot of storage concerns.  @ben-lu-uw do you know why it's necessary?  Even if we have such a button, perhaps it should restore the settings that are in effect when the extension is first installed.

**Comment by bershanskiy** [comment]
I guess, this button allows developer to reset internal state during development. But I usually just call `chrome.storage.local.clear()` directly from the console.

**Comment by ben-lu-uw** [comment]
> Do you know why it's necessary? 

Not sure, when I first saw it, it made sense to me that since we are adding to storage the user should be able to remove everything in storage (which was the original behavior) as well so I just left it there. But yeah we put very little into storage anyways so it does not really matter in the end.

**Comment by prushforth** [comment]
Maybe it was from a learning experience that never got removed.  I would vote to remove it rather than fix bugs in it.

**Comment by bershanskiy** [comment]
> I would vote to remove it rather than fix bugs in it.

Same, filed #40 for this.
